version: 2
jobs:

  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: |
            shellcheck -x .circleci/*.sh

  lint-charts:
    docker:
      - image: gcr.io/kubernetes-charts-ci/test-image:v3.3.2
    steps:
      - checkout
      - run:
          name: lint
          command: |
            git remote add upstream https://github.com/paulczar/percona-helm-charts
            git fetch upstream master
            ct lint --config .circleci/ct.yaml

  release-charts:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "83:f0:ba:b3:b1:ce:c4:ae:34:44:fe:7d:a2:89:5b:d4"
      - run:
          command: |
            echo "export GIT_REPOSITORY_URL=$CIRCLE_REPOSITORY_URL" >> $BASH_ENV
            echo "export GIT_USERNAME=$CIRCLE_PROJECT_USERNAME" >> $BASH_ENV
            echo "export GIT_REPOSITORY_NAME=$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV
            .circleci/install_tools.sh
            .circleci/release.sh

  update-docs:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "83:f0:ba:b3:b1:ce:c4:ae:34:44:fe:7d:a2:89:5b:d4"
      - run:
          command: |
            echo "export GIT_REPOSITORY_URL=$CIRCLE_REPOSITORY_URL" >> $BASH_ENV
            echo "export GIT_USERNAME=$CIRCLE_PROJECT_USERNAME" >> $BASH_ENV
            .circleci/update_docs.sh

workflows:
  version: 2
  lint:
    jobs:
      - lint-scripts
      - lint-charts:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
  release:
    jobs:
      - release-charts:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
      - update-docs:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master