# Default values for pxc-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

finalizers:
  - delete-pxc-pods-in-order
#  - delete-proxysql-pvc
#  - delete-pxc-pvc

nameOverride: ""
fullnameOverride: ""

pxc:
  size: 3
  image:
    repository: percona/percona-xtradb-cluster-operator
    tag: 1.0.0-pxc
  imagePullSecrets: []
  # - name: private-registry-credentials
  readinessDelaySec: 15
  livenessDelaySec: 300
  forceUnsafeBootstrap: false
  ## Uncomment to pass in a mysql config file
  # configuration: |
  #   [mysqld]
  #   wsrep_debug=ON
  #   wsrep_provider_options="gcache.size=1G; gcache.recover=yes"
  resources:
    requests:
      memory: 1G
      cpu: 600m
    limits: {}
      # memory: 1G
      # cpu: 600m
  affinity:
    antiAffinityTopologyKey: "kubernetes.io/hostname"
    # advanced:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #       - matchExpressions:
    #         - key: kubernetes.io/e2e-az-name
    #           operator: In
    #           values:
    #           - e2e-az1
    #           - e2e-az2
  tolerations: []
    # - key: "node.alpha.kubernetes.io/unreachable"
    #   operator: "Exists"
    #   effect: "NoExecute"
    #   tolerationSeconds: 6000
  gracePeriod: 600

secrets:
  passwords:
    root: insecure-root-password
    xtrabackup: insecure-xtrabackup-password
    monitor: insecure-monitor-password
    clustercheck: insecure-clustercheck-password
    proxyadmin: insecure-proxyadmin-password
    pmmserver: insecure-pmmserver-password

# If this is set will not create secrets from values and will instead try to use
# a pre-existing secret of the same name.
clusterSecret: ~

# If this is set will not create secrets from values and will instead try to use
# a pre-existing secret of the same name.
clusterSSLSecret: ~

# If this is set will not create secrets from values and will instead try to use
# a pre-existing secret of the same name.
clusterSSLInternalSecret: ~
