{{- if kindIs "invalid" .Values.watchNamespace }}
kind: RoleBinding
  {{- else }}
kind: ClusterRoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "pxc-operator.fullname" . }}
  {{- if .Values.watchNamespace }}
  namespace: {{ .Values.watchNamespace }}
  {{- end }}
  labels:
{{ include "pxc-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: default
  {{- if not (kindIs "invalid" .Values.watchNamespace) }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  {{- if kindIs "invalid" .Values.watchNamespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "pxc-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
