{{- if not .Values.clusterSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pxc-cluster.fullname" . }}
  labels:
{{ include "pxc-cluster.labels" . | indent 4 }}
type: Opaque
data:
  root: {{ .Values.secrets.passwords.root | b64enc }}
  xtrabackup: {{ .Values.secrets.passwords.xtrabackup | b64enc }}
  monitor: {{ .Values.secrets.passwords.monitor | b64enc }}
  clustercheck: {{ .Values.secrets.passwords.clustercheck | b64enc }}
  proxyadmin: {{ .Values.secrets.passwords.proxyadmin | b64enc }}
  pmmserver: {{ .Values.secrets.passwords.pmmserver | b64enc }}
{{- end -}}